### ISSUE TITLE
Mass Testing at RSECon 2022

### ISSUE THREAD

**Issue by colinsauze** [carpentriesoffline/carpentriesoffline-installer#28]
Instructions:
1. Connect to the WiFi network called carpentries-offline
2. Visit the webpage [http://carpentries-offline.org](http://carpentries-offline.org)
3. Try to download the Windows R package from [http://carpentries-offline.org/R/R-4.2.1-win.exe](http://carpentries-offline.org/R/R-4.2.1-win.exe)
4. Answer the questions below to let us know about any issues. 

Questions:
1. Could you access the webpage at http://carpentries-offline.org?
2. What make/model computer were you using? 
3. What operating system were you using?
4. Were you able to download the R package from http://carpentries-offline.org/R/R-4.2.1-win.exe?
5. Was this downloaded in an acceptable time? If you know how long it took or what data rate you achieved please let us know.

**Comment by manning-ncsa** [comment]
1. Yes
2. Dell XPS 13 7390
3. Linux Ubuntu 22.04.1 LTS
4. Yes
5. Yes. It took about 5 minutes at around 200-300 KB/sec.

**Comment by alisonrclarke** [comment]
1. Yes
2. MacBook Pro (16 inch, 2021), M1 Pro
3. macOS Monterey (12.2)
4. Yes
5. Yes - took around 4 minutes.

**Comment by colinsauze** [comment]
Thanks to everyone who helped with this, it was very useful.
